import './globals.css'

import { Geist, Geist_Mono } from 'next/font/google'

import type { Metadata } from 'next'
import NavLink from '@/components/nav-link'
import { UsersProvider } from '@/components/providers/users-provider'
import { externalApi } from '@/app/api/external'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // I'm cheating here by fetching all the users at once. In a real app, we'd recursively fetch
  // users until we reach had all of them. If orgs typically have lots of users, we'd probably
  // fetch a large set of them, then fill in missing ones from other API calls. /hand waving
  const users = await externalApi.getUsers({ limit: 100 })

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50 p-4`}>
        <header className="flex gap-2 mb-4">
          <NavLink href="/dashboard">Dashboard</NavLink>
          <NavLink href="/conversations">Conversations</NavLink>
          <NavLink href="/policies">Policies</NavLink>
        </header>
        <div className="flex flex-col min-h-screen rounded-lg bg-white p-4 shadow">
          <UsersProvider users={users}>
            <main className="flex-1">{children}</main>
          </UsersProvider>
        </div>
      </body>
    </html>
  )
}
